version: "4.0"
services:
  app:
    depends_on:
      - mysqldb
    image: archer44/spring-boot-todo-app:0.0.4-SNAPSHOT
    container_name: todo-app
    environment:
      - MYSQL_DATABASE=todo_app
      - MYSQL_USER=springtodo
      - MYSQL_PASSWORD=springtodo
    ports:
      - "8080:8080"
    networks:
      - spring-todo
  mysqldb:
    image: mysql:latest
    container_name: todoappdb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=todo_app
      - MYSQL_USER=springtodo
      - MYSQL_PASSWORD=springtodo
    networks:
      - spring-todo
networks:
  spring-todo: {}

